/*

 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ta_abairagency;

/**
 *
 * @author Admin
 */
public class frameGUITA extends javax.swing.JFrame {

    /**
     * Creates new form frameGUITA
     */
    public frameGUITA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOK = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        kolomWaktu = new javax.swing.JTextField();
        kolomJarak = new javax.swing.JTextField();
        kolomMaskapai = new javax.swing.JComboBox<>();
        kolomTujuan = new javax.swing.JComboBox<>();
        kolomNama = new javax.swing.JTextField();
        kolomReport = new javax.swing.JTextArea();
        Report = new javax.swing.JLabel();
        Waktu = new javax.swing.JLabel();
        Jarak = new javax.swing.JLabel();
        Maskapai = new javax.swing.JLabel();
        Tujuan = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        BackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOK.setBackground(new java.awt.Color(204, 204, 204));
        btnOK.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        btnOK.setText("OK");
        btnOK.setToolTipText("");
        btnOK.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        getContentPane().add(btnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 90, 30));

        btnReset.setBackground(new java.awt.Color(204, 204, 204));
        btnReset.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        btnReset.setText("Reset");
        btnReset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 90, 30));

        kolomWaktu.setEditable(false);
        kolomWaktu.setBackground(new java.awt.Color(204, 204, 204));
        kolomWaktu.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        kolomWaktu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(kolomWaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 240, 30));

        kolomJarak.setEditable(false);
        kolomJarak.setBackground(new java.awt.Color(204, 204, 204));
        kolomJarak.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        kolomJarak.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        kolomJarak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolomJarakActionPerformed(evt);
            }
        });
        getContentPane().add(kolomJarak, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 240, 30));

        kolomMaskapai.setBackground(new java.awt.Color(204, 204, 204));
        kolomMaskapai.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        kolomMaskapai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Maskapai", "Batik Air", "Garuda Indonesia", "Air Asia", "Lion Air", "Sriwijaya Air", "Citilink", "ABAir" }));
        kolomMaskapai.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        kolomMaskapai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolomMaskapaiActionPerformed(evt);
            }
        });
        getContentPane().add(kolomMaskapai, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 160, 30));

        kolomTujuan.setBackground(new java.awt.Color(204, 204, 204));
        kolomTujuan.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        kolomTujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Tujuan", "Jakarta - Semarang", "Jakarta - Surabaya", "Yogyakarta - Jakarta", "Denpasar - Jakarta", "Medan - Jakarta", "Denpasar - Balikpapan", "Jakarta - Jayapura", "Makassar - Ambon", "Semarang - Balikpapan" }));
        kolomTujuan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(kolomTujuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 160, 30));

        kolomNama.setBackground(new java.awt.Color(204, 204, 204));
        kolomNama.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        kolomNama.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(kolomNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 160, 30));

        kolomReport.setEditable(false);
        kolomReport.setBackground(new java.awt.Color(204, 204, 204));
        kolomReport.setColumns(20);
        kolomReport.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        kolomReport.setRows(7);
        kolomReport.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(kolomReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 240, 130));

        Report.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        Report.setForeground(new java.awt.Color(153, 0, 0));
        Report.setText("Report");
        getContentPane().add(Report, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 150, 30));

        Waktu.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        Waktu.setForeground(new java.awt.Color(153, 0, 0));
        Waktu.setText("Waktu Tempuh");
        getContentPane().add(Waktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 150, 30));

        Jarak.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        Jarak.setForeground(new java.awt.Color(153, 0, 0));
        Jarak.setText("Jarak Tempuh");
        getContentPane().add(Jarak, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 150, 30));

        Maskapai.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        Maskapai.setForeground(new java.awt.Color(153, 0, 0));
        Maskapai.setText("Maskapai");
        getContentPane().add(Maskapai, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 100, 30));

        Tujuan.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        Tujuan.setForeground(new java.awt.Color(153, 0, 0));
        Tujuan.setText("Tujuan");
        getContentPane().add(Tujuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 100, 30));

        Nama.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        Nama.setForeground(new java.awt.Color(153, 0, 0));
        Nama.setText("Nama");
        getContentPane().add(Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 70, 30));

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ta_abairagency/background.jpg"))); // NOI18N
        getContentPane().add(BackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kolomMaskapaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolomMaskapaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kolomMaskapaiActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
String nama = kolomNama.getText();
int tujuan = kolomTujuan.getSelectedIndex();
int maskapai = kolomMaskapai.getSelectedIndex();
ta_SetGet ambil = new ta_SetGet();
switch(tujuan){
case (0):
    kolomReport.setText("Pilih rute tujuan terlebih dahulu");
case (1):
    ambil.setJarak(450);
    ambil.setWaktu(45);
    break;
case (2) :
    ambil.setJarak(775);
    ambil.setWaktu(80);
    break;
case (3) :
    ambil.setJarak(585);
    ambil.setWaktu(60);
    break;
case (4) : 
    ambil.setJarak(840);
    ambil.setWaktu(85);
    break;
case (5):
    ambil.setJarak(920);
    ambil.setWaktu(95);
    break;
case (6) :
    ambil.setJarak(520);
    ambil.setWaktu(55);
    break;
case (7) :
    ambil.setJarak(2020);
    ambil.setWaktu(205);
    break;
case (8) :
    ambil.setJarak(740);
    ambil.setWaktu(75);
    break;
case (9) :
    ambil.setJarak(380);
    ambil.setWaktu(40);
    break;
 }
 kolomJarak.setText(ambil.getJarak()+" km");
 kolomWaktu.setText(ambil.getWaktu()+" menit");
 kolomReport.setText("Kepada Yth. "+nama+",\npenerbangan pesawat Maskapai "+kolomMaskapai.getItemAt(maskapai)+"\ndengan rute "
 +kolomTujuan.getItemAt(tujuan)+"\nakan menempuh jarak sepanjang "+ambil.getJarak()+" km\ndan membutuhkan waktu sekitar "
 +ambil.getWaktu()+" menit\nTerima kasih sudah menggunakan layanan\nABAir Agency");
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
kolomNama.setText("");
kolomTujuan.setSelectedItem("Pilih Tujuan");
kolomMaskapai.setSelectedItem("Pilih Maskapai");
kolomJarak.setText("");
kolomWaktu.setText("");
kolomReport.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void kolomJarakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolomJarakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kolomJarakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameGUITA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameGUITA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameGUITA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameGUITA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameGUITA().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JLabel Jarak;
    private javax.swing.JLabel Maskapai;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel Report;
    private javax.swing.JLabel Tujuan;
    private javax.swing.JLabel Waktu;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnReset;
    private javax.swing.JTextField kolomJarak;
    private javax.swing.JComboBox<String> kolomMaskapai;
    private javax.swing.JTextField kolomNama;
    private javax.swing.JTextArea kolomReport;
    private javax.swing.JComboBox<String> kolomTujuan;
    private javax.swing.JTextField kolomWaktu;
    // End of variables declaration//GEN-END:variables
}
